heartbeat.monitors:
- type: http
  id: shared-service
  name: Shared Service
  schedule: '@every 20s'
  urls:
    - http://13.228.25.85:8703/ottopoint/v0.1.0/redis//healthcheck-redisservice

- type: http
  id: ottopoint-product
  name: Ottopoint Product
  schedule: '@every 20s'
  urls:
    - https://apidev.ottopoint.id/product/   
  check.response.status: [404]

- type: http
  id: ottopoint-loyalty
  name: Ottopoint Loyalty
  schedule: '@every 60s'
  urls:
    - https://apisrv.ottopoint.id/loyalty/
  check.response.status: [404]

- type: http
  id: ottopoint-transaction
  name: Ottopoint Transaction
  schedule: '@every 20s'
  urls:
    - https://apidev.ottopoint.id/transaction/
  check.response.status: [404]

- type: http
  id: openloyalty
  name: Open Loyalty
  schedule: '@every 30s'
  urls:
    - https://apisrv.ottopoint.id/product/v2/healthcheck-opl
  check.response.status: [200]

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'localhost:9200'
  username: 'elastic'
  password: 'ewfewgew234565'