version: '3'
services:
  web:
    image: httpd
    ports:
      - "81:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  # fluentd-ui:
  #   image: dvladnik/fluentd-ui
  #   ports:
  #     - "9292:9292"
  fluentd:
    build: ./fluentd
    #image: fluent/fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      #- "xpack.security.enabled=true"
      # - "xpack.monitoring.enabled=false"
      # - "xpack.graph.enabled:=false"
      # - "xpack.watcher.enabled=false"
      # - "searchguard.ssl.http.enabled=true"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./docker-data-volumes/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    

  kibana:
    image: kibana:7.9.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml