
image:
	@docker build --tag voucherag-transaction .
run: 
	@docker-compose up -d 
stop:
	@docker-compose down
exec:
	@docker exec -ti voucherag-transaction sh
logs:
	@docker logs -f voucherag-transaction