version: '3.3'

services: 
    api:
        build: "."
        ports:
            - "5000"
        restart: "always"
        networks: 
            - "api.network"
        deploy:
            replicas: 2
    nginx:
        image: nginx:1.15
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "80:80"
        networks: 
            - "api.network"
networks: 
    api.network: